/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MisePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types/index.ts
var DEFAULT_SETTINGS = {
  recipesFolder: "Life/Household/Kitchen/Recipes",
  mealPlanFolder: "Life/Household/Kitchen/Meal Plans",
  shoppingListFolder: "Life/Household/Shopping Lists",
  autoArchiveShoppingLists: "off",
  aisles: [
    { name: "Produce", keywords: ["lettuce", "tomato", "onion", "garlic", "pepper", "apple", "lemon", "lime", "orange", "banana", "potato", "carrot", "celery", "broccoli", "spinach"] },
    { name: "Dairy", keywords: ["milk", "cheese", "butter", "cream", "yogurt", "sour cream", "eggs"] },
    { name: "Meat", keywords: ["chicken", "beef", "pork", "steak", "ground", "bacon", "sausage", "turkey", "fish", "salmon", "shrimp"] },
    { name: "Bakery", keywords: ["bread", "buns", "tortillas", "rolls", "bagels"] },
    { name: "Pantry", keywords: ["pasta", "rice", "flour", "sugar", "oil", "vinegar", "sauce", "broth", "stock", "beans", "canned"] },
    { name: "Frozen", keywords: ["frozen", "ice cream"] },
    { name: "Beverages", keywords: ["soda", "juice", "water", "coffee", "tea"] }
  ],
  mealPlanInsertOptions: {
    includeLink: true,
    includeServings: false,
    includeTime: false,
    includeIngredientsInline: false,
    includeIngredientsCallout: false,
    includeSource: false
  }
};

// src/services/RecipeIndexer.ts
var import_obsidian = require("obsidian");
var RecipeIndexer = class extends import_obsidian.Events {
  constructor(app, settings) {
    super();
    this.recipes = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
  }
  /**
   * Initialize the indexer and perform initial scan
   */
  async initialize() {
    console.log("RecipeIndexer: Ready (not yet implemented)");
  }
  /**
   * Get all indexed recipes
   */
  getRecipes() {
    return Array.from(this.recipes.values());
  }
  /**
   * Get a specific recipe by path
   */
  getRecipe(path) {
    return this.recipes.get(path);
  }
  /**
   * Clean up event listeners
   */
  destroy() {
  }
};

// src/services/MealPlanService.ts
var MealPlanService = class {
  constructor(app, settings, indexer) {
    this.app = app;
    this.settings = settings;
    this.indexer = indexer;
  }
  /**
   * Get the current month's meal plan
   */
  async getCurrentPlan() {
    console.log("MealPlanService: Not yet implemented");
    return null;
  }
  /**
   * Add a recipe to a specific day/meal
   */
  async addMeal(date, meal, recipePath) {
    console.log("MealPlanService.addMeal: Not yet implemented");
  }
};

// src/services/ShoppingListService.ts
var ShoppingListService = class {
  constructor(app, settings, indexer) {
    this.app = app;
    this.settings = settings;
    this.indexer = indexer;
  }
  /**
   * Generate a shopping list for a date range
   */
  async generateList(startDate, endDate, mode = "normal") {
    console.log("ShoppingListService.generateList: Not yet implemented");
    return {
      generatedAt: (/* @__PURE__ */ new Date()).toISOString(),
      dateRange: { start: startDate, end: endDate },
      mode,
      aisles: []
    };
  }
  /**
   * Write shopping list to a file
   */
  async writeListToFile(list) {
    console.log("ShoppingListService.writeListToFile: Not yet implemented");
    return "";
  }
};

// src/ui/settings/MiseSettingsTab.ts
var import_obsidian3 = require("obsidian");

// src/ui/components/FolderSuggest.ts
var import_obsidian2 = require("obsidian");
var FolderSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.textInput = inputEl;
    this.folders = this.getFolders();
  }
  getFolders() {
    return this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian2.TFolder).sort((a, b) => a.path.localeCompare(b.path));
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    return this.folders.filter(
      (folder) => folder.path.toLowerCase().includes(lowerQuery)
    );
  }
  renderSuggestion(folder, el) {
    el.createEl("div", { text: folder.path, cls: "mise-folder-suggestion" });
  }
  selectSuggestion(folder) {
    this.textInput.value = folder.path;
    this.textInput.trigger("input");
    this.close();
  }
};

// src/ui/settings/MiseSettingsTab.ts
var MiseSettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Mise Settings" });
    containerEl.createEl("p", {
      text: "Configure your culinary operating system.",
      cls: "mise-settings-description"
    });
    containerEl.createEl("h2", { text: "\u{1F4C1} Folder Paths" });
    new import_obsidian3.Setting(containerEl).setName("Recipes Folder").setDesc("The folder containing your recipe markdown files.").addText((text) => {
      text.setPlaceholder("Type to search folders...").setValue(this.plugin.settings.recipesFolder).onChange(async (value) => {
        this.plugin.settings.recipesFolder = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian3.Setting(containerEl).setName("Meal Plan Folder").setDesc("The folder where meal plan files are stored.").addText((text) => {
      text.setPlaceholder("Type to search folders...").setValue(this.plugin.settings.mealPlanFolder).onChange(async (value) => {
        this.plugin.settings.mealPlanFolder = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian3.Setting(containerEl).setName("Shopping List Folder").setDesc("The folder where shopping lists are generated.").addText((text) => {
      text.setPlaceholder("Type to search folders...").setValue(this.plugin.settings.shoppingListFolder).onChange(async (value) => {
        this.plugin.settings.shoppingListFolder = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    containerEl.createEl("h2", { text: "\u{1F6D2} Shopping Lists" });
    new import_obsidian3.Setting(containerEl).setName("Auto-archive Shopping Lists").setDesc("What to do with old shopping lists when generating new ones.").addDropdown((dropdown) => dropdown.addOption("off", "Off - Keep all lists in place").addOption("on", "On - Automatically archive").addOption("ask", "Ask every time").setValue(this.plugin.settings.autoArchiveShoppingLists).onChange(async (value) => {
      this.plugin.settings.autoArchiveShoppingLists = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "\u{1F4C5} Meal Plan Insertion" });
    containerEl.createEl("p", {
      text: "Configure what gets inserted when you add a recipe to a meal plan.",
      cls: "mise-settings-description"
    });
    const insertOptions = this.plugin.settings.mealPlanInsertOptions;
    new import_obsidian3.Setting(containerEl).setName("Include Servings").setDesc("Add servings info when inserting a recipe.").addToggle((toggle) => toggle.setValue(insertOptions.includeServings).onChange(async (value) => {
      this.plugin.settings.mealPlanInsertOptions.includeServings = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include Prep/Cook Time").setDesc("Add time information when inserting a recipe.").addToggle((toggle) => toggle.setValue(insertOptions.includeTime).onChange(async (value) => {
      this.plugin.settings.mealPlanInsertOptions.includeTime = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include Ingredients (Inline)").setDesc("Add a comma-separated ingredient list.").addToggle((toggle) => toggle.setValue(insertOptions.includeIngredientsInline).onChange(async (value) => {
      this.plugin.settings.mealPlanInsertOptions.includeIngredientsInline = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include Ingredients (Callout)").setDesc("Add ingredients in a collapsible callout block.").addToggle((toggle) => toggle.setValue(insertOptions.includeIngredientsCallout).onChange(async (value) => {
      this.plugin.settings.mealPlanInsertOptions.includeIngredientsCallout = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include Source Link").setDesc("Add the source URL if available.").addToggle((toggle) => toggle.setValue(insertOptions.includeSource).onChange(async (value) => {
      this.plugin.settings.mealPlanInsertOptions.includeSource = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "\u{1F3EA} Aisle Configuration" });
    containerEl.createEl("p", {
      text: "Customize how ingredients are grouped into aisles. (Coming in a future update)",
      cls: "mise-settings-description"
    });
    const aisleList = containerEl.createEl("div", { cls: "mise-aisle-list" });
    for (const aisle of this.plugin.settings.aisles) {
      aisleList.createEl("p", {
        text: `\u2022 ${aisle.name}: ${aisle.keywords.slice(0, 5).join(", ")}...`,
        cls: "mise-settings-description"
      });
    }
    containerEl.createEl("h2", { text: "\u2699\uFE0F Advanced" });
    new import_obsidian3.Setting(containerEl).setName("Reset to Defaults").setDesc("Reset all settings to their default values.").addButton((button) => button.setButtonText("Reset").setWarning().onClick(async () => {
      this.plugin.settings = { ...DEFAULT_SETTINGS };
      await this.plugin.saveSettings();
      this.display();
    }));
  }
};

// src/utils/constants.ts
var PLUGIN_NAME = "Mise";

// src/main.ts
var MisePlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log(`${PLUGIN_NAME}: Loading plugin...`);
    await this.loadSettings();
    this.indexer = new RecipeIndexer(this.app, this.settings);
    this.mealPlanService = new MealPlanService(this.app, this.settings, this.indexer);
    this.shoppingListService = new ShoppingListService(this.app, this.settings, this.indexer);
    this.addSettingTab(new MiseSettingsTab(this.app, this));
    this.addCommand({
      id: "open-cookbook",
      name: "Open Cookbook",
      callback: () => {
        console.log(`${PLUGIN_NAME}: Open Cookbook command (not yet implemented)`);
      }
    });
    this.addCommand({
      id: "generate-shopping-list",
      name: "Generate Shopping List",
      callback: () => {
        console.log(`${PLUGIN_NAME}: Generate Shopping List command (not yet implemented)`);
      }
    });
    await this.indexer.initialize();
    console.log(`${PLUGIN_NAME}: Plugin loaded successfully!`);
  }
  async onunload() {
    var _a;
    console.log(`${PLUGIN_NAME}: Unloading plugin...`);
    (_a = this.indexer) == null ? void 0 : _a.destroy();
    console.log(`${PLUGIN_NAME}: Plugin unloaded.`);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
